apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-adm-front
  labels:
    app: admin-adm-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-adm-front
  template:
    metadata:
      labels:
        app: admin-adm-front
    spec:
      containers:
        - name: admin-adm-front
          image: ghcr.io/ificu/admin-eam-front
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 80
