apiVersion: v1
kind: Service
metadata:
  name: admin-adm-front
  labels:
    app: admin-adm-front
spec:
  type: ClusterIP
  selector:
    app: admin-adm-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
